# Generated by Django 4.2.23 on 2025-08-28 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyDictionary",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("registration_authority", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("inactive", "Inactive"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        help_text="Dictionary-specific extended attributes",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Flexible JSON field for storing additional dictionary metadata",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_of_activation", models.DateTimeField(blank=True, null=True)),
                ("date_of_deprecation", models.DateTimeField(blank=True, null=True)),
                ("date_of_deactivation", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_dictionaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_dictionaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Dictionary",
                "verbose_name_plural": "Property Dictionaries",
                "ordering": ["-is_default", "name"],
            },
        ),
    ]
