# Generated by Django 4.2.23 on 2025-09-12 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_externallibrary_libraryimport_libraryitem_and_more"),
        ("dictionaries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertydictionary",
            name="default_library",
            field=models.ForeignKey(
                blank=True,
                help_text="Default lookup library for this dictionary",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="properties.externallibrary",
            ),
        ),
    ]
