# Generated by Django 4.2.23 on 2025-08-28 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dictionaries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyGroup",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("class", "Class"),
                            ("domain", "Domain"),
                            ("reference_document", "Reference Document"),
                            ("composed_property", "Composed Property"),
                            ("alternative_use", "Alternative Use"),
                            ("collection", "Collection"),
                            ("derived_quantity", "Derived Quantity"),
                            ("base_quantity", "Base Quantity"),
                            ("template", "Template"),
                            ("functional", "Functional Group"),
                            ("classification", "Classification Group"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        help_text="Store GA codes like GA0001-GA0005 for non-standard group attributes",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Flexible JSON field for storing additional group metadata",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="dictionaries.propertydictionary",
                    ),
                ),
                (
                    "parent_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_groups",
                        to="groups.propertygroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Group",
                "verbose_name_plural": "Property Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PropertyGroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.propertygroup",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Membership",
                "verbose_name_plural": "Group Memberships",
                "ordering": ["order"],
                "unique_together": {("group", "property")},
            },
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="properties",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups",
                through="groups.PropertyGroupMembership",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="GroupName",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=10)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="groups.propertygroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Name",
                "verbose_name_plural": "Group Names",
                "unique_together": {("group", "language")},
            },
        ),
        migrations.CreateModel(
            name="GroupDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("definition", models.TextField()),
                ("language", models.CharField(max_length=10)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="definitions",
                        to="groups.propertygroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Definition",
                "verbose_name_plural": "Group Definitions",
                "unique_together": {("group", "language")},
            },
        ),
    ]
