# Generated by Django 4.2.23 on 2025-09-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupdefinition",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="groupname",
            unique_together=set(),
        ),
    ]
