# Generated by Django 4.2.23 on 2025-11-09 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dictionaries", "0002_propertydictionary_default_library"),
        ("groups", "0002_alter_groupdefinition_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupdefinition",
            options={
                "verbose_name": "Group Definition",
                "verbose_name_plural": "Group Definitions (GA017: Definitions in language N)",
            },
        ),
        migrations.AlterModelOptions(
            name="groupname",
            options={
                "verbose_name": "Group Name",
                "verbose_name_plural": "Group Names (GA016: Names in language N)",
            },
        ),
        migrations.AlterModelOptions(
            name="propertygroupmembership",
            options={
                "ordering": ["order", "property"],
                "verbose_name": "Group Membership",
                "verbose_name_plural": "Group Memberships",
            },
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="activated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date after which the group can be used (GA004)",
                null=True,
                verbose_name="Date of activation",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="category",
            field=models.CharField(
                choices=[
                    ("alternative_use", "Alternative use"),
                    ("class", "Class"),
                    ("composed_property", "Composed property"),
                    ("domain", "Domain"),
                    ("reference_document", "Reference document"),
                ],
                default="class",
                help_text="Indicates which of 5 categories (GA022)",
                max_length=20,
                verbose_name="Category of group",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="countries_of_use",
            field=models.JSONField(
                blank=True,
                help_text="Country(ies) of applicability (ISO 3166-1) (GA019)",
                null=True,
                verbose_name="Country of use",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="country_of_origin",
            field=models.CharField(
                blank=True,
                help_text="Where requirement originated (ISO 3166-1) (GA021)",
                max_length=2,
                null=True,
                verbose_name="Country of origin",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="creators_language",
            field=models.CharField(
                default="en-EN",
                help_text="Language of creator (ISO 639) (GA015)",
                max_length=10,
                verbose_name="Creator's language",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="deactivated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date group becomes obsolete (GA008)",
                null=True,
                verbose_name="Date of deactivation",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="deprecation_explanation",
            field=models.TextField(
                blank=True,
                help_text="Reason for deprecation in English (GA013)",
                null=True,
                verbose_name="Deprecation explanation",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="interconnected_dictionaries",
            field=models.JSONField(
                blank=True,
                help_text="Pairs (internalID, dataDictionaryID) for interconnected dictionaries (GA014)",
                null=True,
                verbose_name="Relation of group IDs in interconnected data dictionaries",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="replaced_groups",
            field=models.JSONField(
                blank=True,
                help_text="GUID(s) of groups replaced by this one (GA011)",
                null=True,
                verbose_name="List of replaced groups",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="replacing_groups",
            field=models.JSONField(
                blank=True,
                help_text="GUID(s) of groups replacing this one (GA012)",
                null=True,
                verbose_name="List of replacing groups",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="revision_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date of the revision (GA006)",
                null=True,
                verbose_name="Date of revision",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="revision_number",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minor-change tracking (GA010)",
                verbose_name="Revision number",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="inactive",
                help_text="Status of the group during its life cycle (GA002)",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="subdivisions_of_use",
            field=models.JSONField(
                blank=True,
                help_text="Geographical region within country (ISO 3166-2) (GA020)",
                null=True,
                verbose_name="Subdivision of use",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="version_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date of the version (GA007)",
                null=True,
                verbose_name="Date of version",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="version_number",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Major-change tracking (GA009)",
                verbose_name="Version number",
            ),
        ),
        migrations.AddField(
            model_name="propertygroup",
            name="visual_representation",
            field=models.JSONField(
                blank=True,
                help_text="Sketch/photo/video/URL for visual representation (GA018)",
                null=True,
                verbose_name="Visual representation",
            ),
        ),
        migrations.AlterField(
            model_name="groupdefinition",
            name="definition",
            field=models.TextField(
                help_text="Group definition in specified language (GA017)",
                verbose_name="Definition",
            ),
        ),
        migrations.AlterField(
            model_name="groupdefinition",
            name="language",
            field=models.CharField(
                help_text="ISO 639 language code (e.g., en-EN, fr-FR)",
                max_length=10,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="groupname",
            name="language",
            field=models.CharField(
                help_text="ISO 639 language code (e.g., en-EN, fr-FR)",
                max_length=10,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="groupname",
            name="name",
            field=models.CharField(
                help_text="Group name in specified language (GA016)",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="propertygroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date of validation of group-creation request (GA003)",
                verbose_name="Date of creation",
            ),
        ),
        migrations.AlterField(
            model_name="propertygroup",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this group",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="propertygroup",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Primary description (use GroupDefinition model for multi-language support)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="propertygroup",
            name="dictionary",
            field=models.ForeignKey(
                help_text="Property dictionary this group belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="dictionaries.propertydictionary",
            ),
        ),
        migrations.AlterField(
            model_name="propertygroup",
            name="extended_attributes",
            field=models.JSONField(
                blank=True,
                help_text="Store additional GA codes (GA0001-GA9999) for non-standard group attributes",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="propertygroup",
            name="guid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Globally unique identifier for the property group (GA001)",
                primary_key=True,
                serialize=False,
                verbose_name="Globally unique identifier",
            ),
        ),
        migrations.AlterField(
            model_name="propertygroup",
            name="name",
            field=models.CharField(
                help_text="Primary name (use GroupName model for multi-language support)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="propertygroup",
            name="parent_group",
            field=models.ForeignKey(
                blank=True,
                help_text="GUID of parent group (for tree structure) (GA023)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_groups",
                to="groups.propertygroup",
                verbose_name="Parent group of properties",
            ),
        ),
        migrations.AlterField(
            model_name="propertygroup",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("class", "Class"),
                    ("domain", "Domain"),
                    ("reference_document", "Reference Document"),
                    ("composed_property", "Composed Property"),
                    ("alternative_use", "Alternative Use"),
                    ("collection", "Collection"),
                    ("derived_quantity", "Derived Quantity"),
                    ("base_quantity", "Base Quantity"),
                    ("template", "Template"),
                    ("functional", "Functional Group"),
                    ("classification", "Classification Group"),
                ],
                help_text="Deprecated: Use 'category' field instead",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="propertygroup",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date of validation of last change request (GA005)",
                verbose_name="Date of last change",
            ),
        ),
        migrations.AlterField(
            model_name="propertygroup",
            name="updated_by",
            field=models.ForeignKey(
                help_text="User who last updated this group",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="propertygroupmembership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="groups.propertygroup",
            ),
        ),
        migrations.AlterField(
            model_name="propertygroupmembership",
            name="is_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether this property is required in the group",
            ),
        ),
        migrations.AlterField(
            model_name="propertygroupmembership",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="Additional metadata for this membership",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="propertygroupmembership",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order of property within the group"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupdefinition",
            unique_together={("group", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="groupname",
            unique_together={("group", "language")},
        ),
        migrations.AddIndex(
            model_name="groupdefinition",
            index=models.Index(
                fields=["language"], name="groups_grou_languag_2b4ca1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupname",
            index=models.Index(
                fields=["language"], name="groups_grou_languag_81963c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertygroup",
            index=models.Index(fields=["status"], name="groups_prop_status_7792b1_idx"),
        ),
        migrations.AddIndex(
            model_name="propertygroup",
            index=models.Index(
                fields=["category"], name="groups_prop_categor_7b3e52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertygroup",
            index=models.Index(
                fields=["created_at"], name="groups_prop_created_7a9fc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertygroup",
            index=models.Index(
                fields=["version_number", "revision_number"],
                name="groups_prop_version_577dc0_idx",
            ),
        ),
    ]
