# Generated by Django 4.2.23 on 2025-11-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_alter_groupdefinition_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupname",
            unique_together=set(),
        ),
    ]
