# Generated by Django 4.2.23 on 2025-11-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_alter_groupname_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupdefinition",
            unique_together=set(),
        ),
    ]
