# Generated by Django 4.2.23 on 2025-08-28 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dictionaries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysicalQuantity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("base", "Base Quantity"),
                            ("derived", "Derived Quantity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "formula",
                    models.CharField(
                        blank=True,
                        help_text="For derived quantities, the formula in terms of base quantities",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Physical Quantity",
                "verbose_name_plural": "Physical Quantities",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "revision_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date_of_activation", models.DateTimeField(blank=True, null=True)),
                ("date_of_version", models.DateTimeField(blank=True, null=True)),
                ("date_of_revision", models.DateTimeField(blank=True, null=True)),
                ("date_of_last_change", models.DateTimeField(auto_now=True)),
                ("date_of_deactivation", models.DateTimeField(blank=True, null=True)),
                ("date_of_deprecation", models.DateTimeField(blank=True, null=True)),
                (
                    "registration_authority",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("registration_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("candidate", "Candidate"),
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("inactive", "Inactive"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("deprecation_explanation", models.TextField(blank=True)),
                ("country_of_origin", models.CharField(blank=True, max_length=50)),
                ("countries_of_use", models.JSONField(blank=True, null=True)),
                ("creators_language", models.CharField(default="en-EN", max_length=10)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("real", "Real"),
                            ("boolean", "Boolean"),
                            ("complex", "Complex"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unit_of_measurement", models.CharField(blank=True, max_length=50)),
                ("value_domain", models.JSONField(blank=True, null=True)),
                (
                    "classification_system",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "classification_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        help_text="Store PA codes like PA0001-PA0010 for non-standard property attributes",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Flexible JSON field for storing additional metadata",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="dictionaries.propertydictionary",
                    ),
                ),
                (
                    "physical_quantity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="properties",
                        to="properties.physicalquantity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("parent-child", "Parent-Child"),
                            ("dependency", "Dependency"),
                            ("alternative", "Alternative"),
                            ("equivalent", "Equivalent"),
                            ("component", "Component"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "source_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="properties.property",
                    ),
                ),
                (
                    "target_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Relationship",
                "verbose_name_plural": "Property Relationships",
                "unique_together": {
                    ("source_property", "target_property", "relationship_type")
                },
            },
        ),
        migrations.CreateModel(
            name="PropertyName",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=10)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Name",
                "verbose_name_plural": "Property Names",
                "unique_together": {("property", "language")},
            },
        ),
        migrations.CreateModel(
            name="PropertyDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("definition", models.TextField()),
                ("language", models.CharField(max_length=10)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="definitions",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Definition",
                "verbose_name_plural": "Property Definitions",
                "unique_together": {("property", "language")},
            },
        ),
    ]
