# Generated by Django 4.2.23 on 2025-08-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="propertyname",
            unique_together=set(),
        ),
    ]
