# Generated by Django 4.2.23 on 2025-08-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_propertyname_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="propertydefinition",
            unique_together=set(),
        ),
    ]
