# Generated by Django 4.2.23 on 2025-09-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_add_pa_code"),
        ("properties", "0003_alter_propertydefinition_unique_together"),
    ]

    operations = []
