# Generated by Django 4.2.23 on 2025-09-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_merge_20250901_1405"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="boundary_values",
            field=models.JSONField(
                blank=True, help_text="Boundary intervals and units", null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="defining_names",
            field=models.JSONField(
                blank=True, help_text="Names of defining values (for arrays)", null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="defining_values",
            field=models.JSONField(
                blank=True, help_text="Actual header values for arrays", null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="digital_format",
            field=models.JSONField(
                blank=True,
                help_text="Numeric/digital format (precision etc.)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="dimension",
            field=models.JSONField(
                blank=True,
                help_text='Dimension exponent vector (e.g. {"L":1, "T":-2})',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="dynamic_property",
            field=models.BooleanField(
                default=False, help_text="Is this property a computed/dynamic property?"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="external_identifiers",
            field=models.JSONField(
                blank=True, help_text="Map of external dictionary IDs", null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="method_of_measurement",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="parameter_properties",
            field=models.ManyToManyField(
                blank=True, related_name="parameter_of", to="properties.property"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="permissible_units",
            field=models.JSONField(
                blank=True, help_text="Optional list of permissible units", null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_media",
            field=models.JSONField(
                blank=True, help_text="Media entries: url, type, caption", null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="replaced_properties",
            field=models.ManyToManyField(
                blank=True,
                related_name="replacing_properties",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="subdivisions_of_use",
            field=models.JSONField(
                blank=True,
                help_text="Optional subdivisions/regions (ISO3166-2)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="text_format",
            field=models.CharField(
                blank=True, help_text="Text encoding/format details", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="tolerance",
            field=models.JSONField(
                blank=True, help_text="Tolerance information", null=True
            ),
        ),
    ]
