# Generated by Django 4.2.23 on 2025-09-03 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0005_property_boundary_values_property_defining_names_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyExample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("example", models.TextField()),
                ("language", models.CharField(blank=True, max_length=10)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Example",
                "verbose_name_plural": "Property Examples",
            },
        ),
        migrations.CreateModel(
            name="PropertyDescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                ("language", models.CharField(blank=True, max_length=10)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Description",
                "verbose_name_plural": "Property Descriptions",
            },
        ),
    ]
