# Generated by Django 4.2.23 on 2025-09-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_propertyexample_propertydescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="pa_code",
            field=models.CharField(
                blank=True,
                help_text="Optional handcrafted PA identifier (e.g., PA001, PA002). Must be unique if provided.",
                max_length=20,
                null=True,
                verbose_name="PA Code ",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("candidate", "Candidate"),
                    ("active", "Active"),
                    ("deprecated", "Deprecated"),
                    ("inactive", "Inactive"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                help_text="Status of the property during its life cycle",
                max_length=20,
                verbose_name="Status (PA002)",
            ),
        ),
    ]
