# Generated by Django 4.2.23 on 2025-09-12 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dictionaries", "0001_initial"),
        ("properties", "0007_alter_property_pa_code_alter_property_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalLibrary",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("dictionary", "Dictionary"),
                            ("user", "User"),
                        ],
                        default="global",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("version", models.CharField(default="1", max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dictionary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionaries.propertydictionary",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LibraryImport",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("filename", models.CharField(max_length=255)),
                ("raw", models.BinaryField()),
                ("content_type", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "library",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.externallibrary",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LibraryItem",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("label", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="properties.externallibrary",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "label"],
                "unique_together": {("library", "code")},
            },
        ),
        migrations.AddIndex(
            model_name="externallibrary",
            index=models.Index(fields=["slug"], name="properties__slug_40bec2_idx"),
        ),
        migrations.AddIndex(
            model_name="externallibrary",
            index=models.Index(
                fields=["scope", "dictionary"], name="properties__scope_034905_idx"
            ),
        ),
    ]
