# Generated by Django 4.2.23 on 2025-09-12 06:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_externallibrary_libraryimport_libraryitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldLibraryBinding",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "target_model",
                    models.CharField(
                        help_text="app.ModelName e.g. properties.Property",
                        max_length=255,
                    ),
                ),
                (
                    "target_field",
                    models.CharField(
                        help_text="field name e.g. unit_item", max_length=200
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FieldLibraryBindingEntry",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "filter_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Optional filter e.g. {"active": true, "code__startswith":"k"}',
                    ),
                ),
                (
                    "transform_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Optional transform e.g. {"label_prefix":"(std) "}',
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="properties.fieldlibrarybinding",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.externallibrary",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
