# Generated by Django 4.2.23 on 2025-08-28 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("requests", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="The type of entity being audited (Property, Group, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        help_text="The UUID of the entity being audited", max_length=100
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("activate", "Activate"),
                            ("deactivate", "Deactivate"),
                            ("deprecate", "Deprecate"),
                            ("restore", "Restore"),
                            ("status_change", "Status Change"),
                            ("relationship_add", "Add Relationship"),
                            ("relationship_remove", "Remove Relationship"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("implement", "Implement"),
                            ("submit", "Submit"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("data_before", models.JSONField(blank=True, null=True)),
                ("data_after", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "extended_attributes",
                    models.JSONField(
                        blank=True,
                        help_text="Store DA codes like DA0001-DA0005 for audit-specific attributes",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Flexible JSON field for storing additional audit metadata",
                        null=True,
                    ),
                ),
                (
                    "change_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="requests.changerequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_audit_entity__a4a3e7_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_audit_timesta_787318_idx"
                    ),
                    models.Index(
                        fields=["user"], name="audit_audit_user_id_7b3d5c_idx"
                    ),
                    models.Index(
                        fields=["action"], name="audit_audit_action_4c6da2_idx"
                    ),
                ],
            },
        ),
    ]
